<!-- LOAD PLUGIN JS FILES -->
<script type="text/javascript" src="/node_modules/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="/node_modules/popper.js/dist/umd/popper.min.js"></script>
<script type="text/javascript" src="/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/node_modules/noty/lib/noty.min.js"></script>
<script type="text/javascript" src="/node_modules/moment/min/moment-with-locales.min.js"></script>
<script type="text/javascript" src="/node_modules/perfect-scrollbar/dist/perfect-scrollbar.min.js"></script>
<script type="text/javascript" src="/assets/js/hashchange.min.js"></script>
<script type="text/javascript" src="/assets/js/app.min.js"></script>


</body>
</html>
